name: Newt_demo_pipeline_2019/classic_pipeline
on:
  workflow_dispatch:
env:
  system_debug: 'false'
jobs:
  Job_1:
    name: Agent job 1
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Command Line Script
      run: echo Hello, welcome to the Azure DevOps Classic Pipeline!
    - name: Command Line Script
      run: echo Hello, welcome to the Azure DevOps Classic Pipeline!   second one
