name: Newt_demo_pipeline_2019/TestRelease
on:
  workflow_dispatch:
env:
  test: '1234'
jobs:
  Stage-1:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
